services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - 12_report_node_modules:/app/node_modules
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - 12_report_pixi:/app/.pixi
      - ./backend:/app

volumes:
  12_report_node_modules:
  12_report_pixi: