services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - /app/.pixi
      - ./backend:/app