/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as F9Import } from './routes/f9'
import { Route as F3Import } from './routes/f3'
import { Route as F2Import } from './routes/f2'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const F9Route = F9Import.update({
  path: '/f9',
  getParentRoute: () => rootRoute,
} as any)

const F3Route = F3Import.update({
  path: '/f3',
  getParentRoute: () => rootRoute,
} as any)

const F2Route = F2Import.update({
  path: '/f2',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/f2': {
      id: '/f2'
      path: '/f2'
      fullPath: '/f2'
      preLoaderRoute: typeof F2Import
      parentRoute: typeof rootRoute
    }
    '/f3': {
      id: '/f3'
      path: '/f3'
      fullPath: '/f3'
      preLoaderRoute: typeof F3Import
      parentRoute: typeof rootRoute
    }
    '/f9': {
      id: '/f9'
      path: '/f9'
      fullPath: '/f9'
      preLoaderRoute: typeof F9Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f2': typeof F2Route
  '/f3': typeof F3Route
  '/f9': typeof F9Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f2': typeof F2Route
  '/f3': typeof F3Route
  '/f9': typeof F9Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/f2': typeof F2Route
  '/f3': typeof F3Route
  '/f9': typeof F9Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/f2' | '/f3' | '/f9'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/f2' | '/f3' | '/f9'
  id: '__root__' | '/' | '/f2' | '/f3' | '/f9'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  F2Route: typeof F2Route
  F3Route: typeof F3Route
  F9Route: typeof F9Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  F2Route: F2Route,
  F3Route: F3Route,
  F9Route: F9Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/f2",
        "/f3",
        "/f9"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/f2": {
      "filePath": "f2.tsx"
    },
    "/f3": {
      "filePath": "f3.tsx"
    },
    "/f9": {
      "filePath": "f9.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
